# Generated by tools/Update-LazyModules.ps1. Implementation stays in the repository root.
@{
    RootModule = '../../GUI-Basic.psm1'
    ModuleVersion = '1.0.0'
    PowerShellVersion = '7.0'
    FunctionsToExport = @('Switch-TaskbarHide', 'Switch-TaskbarClickThrough', 'Find-ExplorerShell')
    AliasesToExport = @()
    CmdletsToExport = @()
    VariablesToExport = @()
}
