# Generated by tools/Update-LazyModules.ps1. Implementation stays in the repository root.
@{
    RootModule = '../../quickWebAction.psm1'
    ModuleVersion = '1.0.0'
    PowerShellVersion = '7.0'
    FunctionsToExport = @('hashmapMatch', 'hvdic', 'Search-DuckDuckGo', 'Resolve-InputUrl', 'Resolve-InputUri', 'Get-ParsedId', 'Select-ID', 'Invoke-SelectedID', 'Invoke-NewsLink')
    AliasesToExport = @('gg', 'id', 'iid', 'hn')
    CmdletsToExport = @()
    VariablesToExport = @()
}
