# Generated by tools/Update-LazyModules.ps1. Aliases point to native autoloaded commands.

function global:Invoke-P7VimCommand {
    param(
        [Parameter(Mandatory)][string]$CommandName,
        [Parameter(ValueFromRemainingArguments)][object[]]$ArgumentList
    )
    $stubPath = "Function:\Global:$CommandName"
    Remove-Item -LiteralPath $stubPath -Force -ErrorAction SilentlyContinue
    Import-Module -Name (Join-Path $env:p7settingDir 'quickVimAction.psm1') -Scope Global -ErrorAction Stop
    & $CommandName @ArgumentList
}

foreach ($commandName in @(':q', ':a', ':r', ':m', ':v', ':vl', ':vs', ':e', ':s', ':k', ':obsidian', ':jrnl', 'jvc')) {
    $quotedName = $commandName.Replace("'", "''")
    Set-Item -Path ("Function:\Global:" + $commandName) -Value ([scriptblock]::Create("param([Parameter(ValueFromRemainingArguments=`$true)][object[]]`$arg); Invoke-P7VimCommand -CommandName '$quotedName' -ArgumentList `$arg")) -Force
}

foreach ($entry in @(
    @{ Name = 'zz'; Value = 'yz'; Options = 'None' }
    @{ Name = 'msmt'; Value = 'Invoke-KeyMouse'; Options = 'None' }
    @{ Name = 'zo'; Value = 'zq'; Options = 'None' }
    @{ Name = 'zoi'; Value = 'zqi'; Options = 'None' }
    @{ Name = 'cdb'; Value = 'zb'; Options = 'None' }
    @{ Name = 'rgr'; Value = 'scooter'; Options = 'None' }
    @{ Name = 'qrlo'; Value = 'rlo'; Options = 'None' }
    @{ Name = 'r'; Value = 'just'; Options = 'AllScope' }
    @{ Name = 'top'; Value = 'btm'; Options = 'None' }
    @{ Name = 'du'; Value = 'dust'; Options = 'None' }
    @{ Name = 'less'; Value = 'tspin'; Options = 'None' }
    @{ Name = 'ls'; Value = 'lsd'; Options = 'AllScope' }
    @{ Name = 'nc'; Value = 'ncat'; Options = 'AllScope' }
    @{ Name = 'Lyric'; Value = 'Add-LyricFile'; Options = 'None' }
    @{ Name = 'Track'; Value = 'Add-NextTrack'; Options = 'None' }
    @{ Name = ':cp'; Value = 'Import-Completion'; Options = 'None' }
    @{ Name = 'jmpv'; Value = 'Get-Playlistmpv'; Options = 'None' }
    @{ Name = 'andDev'; Value = 'androidDevEnv'; Options = 'None' }
    @{ Name = 'adbDev'; Value = 'androidDevEnv'; Options = 'None' }
    @{ Name = 'expl'; Value = 'Start-Explorer'; Options = 'None' }
    @{ Name = 'exp'; Value = 'Start-Explorer'; Options = 'None' }
    @{ Name = 'fz'; Value = 'pocof'; Options = 'None' }
    @{ Name = 'cq'; Value = 'ConvertTo-KeyComboText'; Options = 'None' }
    @{ Name = 'kqn'; Value = 'Search-KeyComboNotes'; Options = 'None' }
    @{ Name = 'cpjust'; Value = 'Copy-Just'; Options = 'None' }
    @{ Name = 'Apply-GitPatch'; Value = 'Invoke-GitApplyPatch'; Options = 'None' }
    @{ Name = 'gccb'; Value = 'gitCloneClipboard'; Options = 'None' }
    @{ Name = 'gui'; Value = 'gitu'; Options = 'None' }
    @{ Name = 'solve'; Value = 'qalc'; Options = 'None' }
    @{ Name = 'cls'; Value = 'clearScrn'; Options = 'AllScope' }
    @{ Name = 'clear'; Value = 'clearScrn'; Options = 'AllScope' }
    @{ Name = 'mpcn'; Value = 'mpn'; Options = 'AllScope' }
    @{ Name = 'shcb'; Value = 'Invoke-ShimClipboardPath'; Options = 'None' }
    @{ Name = 'rvcb'; Value = 'Resolve-ClipboardPath'; Options = 'None' }
    @{ Name = 'cdsl'; Value = 'Set-LocationSymLink'; Options = 'None' }
    @{ Name = 'cdslr'; Value = 'Set-LocationSymLinkRoot'; Options = 'None' }
    @{ Name = 'rsjb'; Value = 'Restart-Job'; Options = 'None' }
    @{ Name = 'spa'; Value = 'Split-Path'; Options = 'AllScope' }
    @{ Name = 'jpa'; Value = 'Join-Path'; Options = 'AllScope' }
    @{ Name = 'mcm'; Value = 'Measure-Command'; Options = 'None' }
    @{ Name = 'rmrf'; Value = 'Remove-FullForce'; Options = 'None' }
    @{ Name = 'cprf'; Value = 'Copy-FullForce'; Options = 'None' }
    @{ Name = 'cpcb'; Value = 'Copy-FileClipboard'; Options = 'None' }
    @{ Name = 'cpdrop'; Value = 'Copy-FileClipboard'; Options = 'None' }
    @{ Name = 'gti'; Value = 'Get-TypeInfo'; Options = 'None' }
    @{ Name = 'gpd'; Value = 'Get-ParameterDefault'; Options = 'None' }
    @{ Name = 'gcbf'; Value = 'Get-FileClipboardPath'; Options = 'None' }
    @{ Name = 'p7mod'; Value = 'Import-MoreModule'; Options = 'None' }
    @{ Name = ':mo'; Value = 'Restart-ModuleList'; Options = 'None' }
    @{ Name = ':o'; Value = ':obsidian'; Options = 'None' }
    @{ Name = 'j'; Value = ':jrnl'; Options = 'None' }
    @{ Name = 'gg'; Value = 'Search-DuckDuckGo'; Options = 'None' }
    @{ Name = 'id'; Value = 'Select-ID'; Options = 'None' }
    @{ Name = 'iid'; Value = 'Invoke-SelectedID'; Options = 'None' }
    @{ Name = 'hn'; Value = 'Invoke-NewsLink'; Options = 'None' }
)) {
    $current = Get-Alias -Name $entry.Name -Scope Global -ErrorAction SilentlyContinue
    if ($current -and ($current.Options -band [Management.Automation.ScopedItemOptions]::AllScope) -and $entry.Options -eq 'None') {
        Remove-Alias -Name $entry.Name -Scope Global -Force
    }
    Set-Alias -Name $entry.Name -Value $entry.Value -Option $entry.Options -Scope Global -Force
}
