# Generated by tools/Update-LazyModules.ps1. Implementation stays in the repository root.
@{
    RootModule = '../../quickFilePathAction.psm1'
    ModuleVersion = '1.0.0'
    PowerShellVersion = '7.0'
    FunctionsToExport = @('EmbedEnv', 'keilLoad', 'Invoke-FlashChip', 'Build-FromKeil', 'Copy-Just')
    AliasesToExport = @('cpjust')
    CmdletsToExport = @()
    VariablesToExport = @()
}
