# Generated by tools/Update-LazyModules.ps1. Implementation stays in the repository root.
@{
    RootModule = '../../CLI-Basic.psm1'
    ModuleVersion = '1.0.0'
    PowerShellVersion = '7.0'
    FunctionsToExport = @('omniSearchObsidian', 'Get-SearchArgs', 'Join-SearchPattern', 'Build-PatternFromPureTokens', 'Get-JournalSearchContext', 'rgj', 'rgo', 'igo', 'igj', 'yz', 'Invoke-SudoPwsh', 'Invoke-KeyMouse', 'Get-PathFromFiles', 'zsh', 'zq', 'zqi', 'zb', 'zbi', 'zqb', 'zqbi', 'ze', 'za', 'zaa', 'ccb', 'rb', 'rt', 'rr', 'rrr', 'rfmt', 'rd', 'rs', 'rw', 're', 'rei', 'rlo', 'f', 'lsd', 'la', 'tree', 'tre', 'trei', 'ncput', 'ncget', 'pcb', 'Send-MpvCommand', 'Get-MpvProperty', 'Select-FileWithFzf', 'Add-LyricFile', 'Add-NextTrack', 'b')
    AliasesToExport = @('zz', 'msmt', 'zo', 'zoi', 'cdb', 'rgr', 'qrlo', 'r', 'top', 'du', 'less', 'ls', 'nc', 'Lyric', 'Track')
    CmdletsToExport = @()
    VariablesToExport = @()
}
