# Generated by tools/Update-LazyModules.ps1. Implementation stays in the repository root.
@{
    RootModule = '../../quickPwshUtils.psm1'
    ModuleVersion = '1.0.0'
    PowerShellVersion = '7.0'
    FunctionsToExport = @('clearScrn', 'Restart-ForceApp', 'Show-Window', 'Send-MpvIpcCommand', 'Send-Key', 'mpn', 'mpns', 'buildIndex', 'filterURI', 'Restart-Job', 'Format-Hyperlink', 'isLink', 'Set-LocationSymLink', 'Set-LocationSymLinkRoot', 'Remove-FullForce', 'Copy-FullForce', 'quickSymLink', 'Get-FileClipboardPath', 'Set-FileClipboard', 'Copy-FileClipboard', 'swap_prompt', 'Convert-PathToOsc8', 'Resolve-ClipboardPath', 'Invoke-ShimClipboardPath', 'Get-TypeInfo', 'Get-ParameterDefault', 'Format-ParameterDefaultValue')
    AliasesToExport = @('cls', 'clear', 'mpcn', 'shcb', 'rvcb', 'cdsl', 'cdslr', 'rsjb', 'spa', 'jpa', 'mcm', 'rmrf', 'cprf', 'cpcb', 'cpdrop', 'gti', 'gpd', 'gcbf')
    CmdletsToExport = @()
    VariablesToExport = @()
}
