# Generated by tools/Update-LazyModules.ps1. Implementation stays in the repository root.
@{
    RootModule = '../../quickTerminalAction.psm1'
    ModuleVersion = '1.0.0'
    PowerShellVersion = '7.0'
    FunctionsToExport = @('term', 'tapscr', 'fontsw', 'swapWtShader', 'copyWtShader')
    AliasesToExport = @()
    CmdletsToExport = @()
    VariablesToExport = @()
}
