# Generated by tools/Update-LazyModules.ps1. Implementation stays in the repository root.
@{
    RootModule = '../../Formatter.psm1'
    ModuleVersion = '1.0.0'
    PowerShellVersion = '7.0'
    FunctionsToExport = @('Format-PowerShellFile')
    AliasesToExport = @()
    CmdletsToExport = @()
    VariablesToExport = @()
}
