# Generated by tools/Update-LazyModules.ps1. Implementation stays in the repository root.
@{
    RootModule = '../../quickGitAction.psm1'
    ModuleVersion = '1.0.0'
    PowerShellVersion = '7.0'
    FunctionsToExport = @('quickInitGit', 'quickDeInitGit', 'Invoke-GitApplyPatch', 'Select-RepoLink', 'gitCloneClipboard')
    AliasesToExport = @('Apply-GitPatch', 'gccb', 'gui')
    CmdletsToExport = @()
    VariablesToExport = @()
}
