# Generated by tools/Update-LazyModules.ps1. Implementation stays in the repository root.
@{
    RootModule = '../../quickMathAction.psm1'
    ModuleVersion = '1.0.0'
    PowerShellVersion = '7.0'
    FunctionsToExport = @('toHex', 'toBin', 'Format-ArrayFromString', 'Format-ReverseArray', 'reverse', 'Split-Batch')
    AliasesToExport = @('solve')
    CmdletsToExport = @()
    VariablesToExport = @()
}
