param([string]$RepositoryRoot = (Split-Path $PSScriptRoot -Parent))

$ErrorActionPreference = 'Stop'
function Quote-Literal([string]$Value) { "'" + $Value.Replace("'", "''") + "'" }
$aliasEntries = [ordered]@{}
$commandNames = [Collections.Generic.List[string]]::new()
foreach ($file in Get-ChildItem -LiteralPath $RepositoryRoot -Filter '*.psm1' -File) {
    if ($file.BaseName -eq 'quickPSReadLine') { continue }
    $tokens = $null
    $errors = $null
    $ast = [Management.Automation.Language.Parser]::ParseFile($file.FullName, [ref]$tokens, [ref]$errors)
    if ($errors) { throw ($errors.Message -join "`n") }
    $functions = @($ast.EndBlock.Statements | Where-Object { $_ -is [Management.Automation.Language.FunctionDefinitionAst] } |
        ForEach-Object { $_.Name -replace '^global:', '' })
    if ($file.BaseName -eq 'quick.query') {
        $functions = @('ConvertTo-KeyComboText', 'ConvertFrom-KeyComboCanonical', 'Find-PSReadLineKeyBinding', 'Get-KeyComboDictionary', 'Search-KeyComboNotes')
    }
    $commandNames.AddRange([string[]]$functions)
    $aliases = @()
    foreach ($statement in $ast.EndBlock.Statements) {
        if ($statement -isnot [Management.Automation.Language.PipelineAst]) { continue }
        foreach ($command in $statement.PipelineElements) {
            if ($command -isnot [Management.Automation.Language.CommandAst] -or $command.GetCommandName() -ne 'Set-Alias') { continue }
            $parts = $command.CommandElements
            $name = $value = $null
            $options = 'None'
            for ($i = 1; $i -lt $parts.Count; $i++) {
                if ($parts[$i] -is [Management.Automation.Language.CommandParameterAst]) {
                    switch ($parts[$i].ParameterName) {
                        Name { $name = $parts[++$i].SafeGetValue() }
                        Value { $value = $parts[++$i].SafeGetValue() }
                        Option { $options = $parts[++$i].SafeGetValue() }
                        Scope { $i++ }
                    }
                }
                elseif (-not $name) { $name = $parts[$i].SafeGetValue() }
                elseif (-not $value) { $value = $parts[$i].SafeGetValue() }
            }
            if (-not $name -or -not $value) { throw "Cannot read alias: $($command.Extent.Text)" }
            $aliases += $name
            $aliasEntries[$name] = @{ Value = $value; Options = $options }
        }
    }
    $directory = Join-Path $RepositoryRoot "modules/$($file.BaseName)"
    $null = New-Item -ItemType Directory -Path $directory -Force
    $functionList = ($functions | ForEach-Object { Quote-Literal $_ }) -join ', '
    $aliasList = (@($aliases | Select-Object -Unique) | ForEach-Object { Quote-Literal $_ }) -join ', '
    $manifest = @"
# Generated by tools/Update-LazyModules.ps1. Implementation stays in the repository root.
@{
    RootModule = '../../$($file.Name)'
    ModuleVersion = '1.0.0'
    PowerShellVersion = '7.0'
    FunctionsToExport = @($functionList)
    AliasesToExport = @($aliasList)
    CmdletsToExport = @()
    VariablesToExport = @()
}
"@
    Set-Content -LiteralPath (Join-Path $directory "$($file.BaseName).psd1") -Value $manifest -Encoding utf8
}

$lines = [Collections.Generic.List[string]]::new()
$lines.Add('# Generated by tools/Update-LazyModules.ps1. Aliases point to native autoloaded commands.')
$colonCommands = @'

function global:Invoke-P7VimCommand {
    param(
        [Parameter(Mandatory)][string]$CommandName,
        [Parameter(ValueFromRemainingArguments)][object[]]$ArgumentList
    )
    $stubPath = "Function:\Global:$CommandName"
    Remove-Item -LiteralPath $stubPath -Force -ErrorAction SilentlyContinue
    Import-Module -Name (Join-Path $env:p7settingDir 'quickVimAction.psm1') -Scope Global -ErrorAction Stop
    & $CommandName @ArgumentList
}

foreach ($commandName in @(':q', ':a', ':r', ':m', ':v', ':vl', ':vs', ':e', ':s', ':k', ':obsidian', ':jrnl', 'jvc')) {
    $quotedName = $commandName.Replace("'", "''")
    Set-Item -Path ("Function:\Global:" + $commandName) -Value ([scriptblock]::Create("param([Parameter(ValueFromRemainingArguments=`$true)][object[]]`$arg); Invoke-P7VimCommand -CommandName '$quotedName' -ArgumentList `$arg")) -Force
}

'@
$lines.Add($colonCommands)
$lines.Add('foreach ($entry in @(')
foreach ($name in $aliasEntries.Keys) {
    $entry = $aliasEntries[$name]
    $lines.Add('    @{ Name = ' + (Quote-Literal $name) + '; Value = ' + (Quote-Literal $entry.Value) + '; Options = ' + (Quote-Literal $entry.Options) + ' }')
}
$lines.Add(')) {')
$lines.Add('    $current = Get-Alias -Name $entry.Name -Scope Global -ErrorAction SilentlyContinue')
$lines.Add('    if ($current -and ($current.Options -band [Management.Automation.ScopedItemOptions]::AllScope) -and $entry.Options -eq ''None'') {')
$lines.Add('        Remove-Alias -Name $entry.Name -Scope Global -Force')
$lines.Add('    }')
$lines.Add('    Set-Alias -Name $entry.Name -Value $entry.Value -Option $entry.Options -Scope Global -Force')
$lines.Add('}')
Set-Content -LiteralPath (Join-Path $RepositoryRoot 'LazyAliases.ps1') -Value $lines -Encoding utf8
