# Generated by tools/Update-LazyModules.ps1. Implementation stays in the repository root.
@{
    RootModule = '../../quick.query.psm1'
    ModuleVersion = '1.0.0'
    PowerShellVersion = '7.0'
    FunctionsToExport = @('ConvertTo-KeyComboText', 'ConvertFrom-KeyComboCanonical', 'Find-PSReadLineKeyBinding', 'Get-KeyComboDictionary', 'Search-KeyComboNotes')
    AliasesToExport = @('cq', 'kqn')
    CmdletsToExport = @()
    VariablesToExport = @()
}
