# Generated by tools/Update-LazyModules.ps1. Implementation stays in the repository root.
@{
    RootModule = '../../CLI-Extra.psm1'
    ModuleVersion = '1.0.0'
    PowerShellVersion = '7.0'
    FunctionsToExport = @('Import-Completion', 'Get-Playlistmpv', 'mpvc', 'Wait-MPVHibernate', 'aliim', 'ptoy', 'rds', 'androidDevEnv', 'Start-Explorer', 'ytlf', 'gdl')
    AliasesToExport = @(':cp', 'jmpv', 'andDev', 'adbDev', 'expl', 'exp', 'fz')
    CmdletsToExport = @()
    VariablesToExport = @()
}
