# Generated by tools/Update-LazyModules.ps1. Implementation stays in the repository root.
@{
    RootModule = '../../quickVimAction.psm1'
    ModuleVersion = '1.0.0'
    PowerShellVersion = '7.0'
    FunctionsToExport = @(':q', ':a', ':r', 'Import-MoreModule', ':m', ':v', ':vl', ':vs', 'Convert-JrnlPathToVaultPath', 'Get-JrnlJournalTable', ':obsidian', ':jrnl', 'jvc', ':e', ':s', ':k')
    AliasesToExport = @('p7mod', ':mo', ':o', 'j')
    CmdletsToExport = @()
    VariablesToExport = @()
}
